version: '3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.4
    environment:
      SERVER_NAME: kibana.lid.org
      ELASTICSEARCH_HOSTS: '["http://lid-es01:9200"]'
      # ELASTICSEARCH_USERNAME: "elastic"
      # ELASTICSEARCH_PASSWORD: "iZDirhr6hOFgxbaJauhn"
    ports:
      - 5601:5601
    networks:
      - efk
networks:
  efk:
    driver: bridge
